import Head from 'next/head'

const Checkout = () => {
  return(
    <div>
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        Checkout
      </h1>
    </div>
  )
}

export default Checkout;