import Head from 'next/head'

const Login = () => {
  return(
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        Login
      </h1>
    </div>
  )
}

export default Login;